
export const nftData = [
    {
      title: "Azuki Elementals",
      floorPrice: 0.30 ,
      totalVolume: 65,
      tokenNumber: 2000,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307952/azuki_rkpsvh.avif",
      category:"top",
    },
    {
      title: "Parallel Avatars",
      floorPrice: 0.65 ,
      totalVolume: 7640 ,
      tokenNumber: 1500,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307950/parralel_j4iffq.avif",
      category:"top",
    
    },
    {
      title: "The Ancients of Hol...",
      floorPrice: 0.04 ,
      totalVolume: 16 ,
      tokenNumber: 500,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307950/acci_b8r9f6.avif",
      category:"top",
    },
    {
      title: "Footium Players",
      floorPrice: 0.01 ,
      totalVolume: 364 ,
      tokenNumber: 1800,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307951/footi_mqb8pw.avif",
      category:"top",
    },
    {
      title: "OCH Genesis Ring",
      floorPrice: 1.95 ,
      totalVolume: 3.328,
      tokenNumber: 1200,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307951/OCH_xxeiu4.avif",
      category:"gaming",
  
    },
    {
      title: "BredApeYuriClub",
      floorPrice: 0.01 ,
      totalVolume: 3.348 ,
      tokenNumber: 800,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738307953/bredapi_yptx8f.avif",
      category:"gaming",
    },
    {
      title: "Mutant Hound Collars",
      floorPrice: 0.98 ,
      totalVolume: 11 ,
      tokenNumber: 3000,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342710/wvprs_i1fuj6.avif",
      category:"gaming",
    },
    {
      title: "Doodles",
      floorPrice: 2.50 ,
      totalVolume: 150,
      tokenNumber: 5000,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342714/pudgypingles_cw5l7x.avif",
      category:"gaming",
    },
    {
      title: "CloneX",
      floorPrice: 1.75 ,
      totalVolume: 78 ,
      tokenNumber: 3500,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342709/piple_fz6f1v.avif",
      category:"meta",
    },
    {
      title: "Moonbirds",
      floorPrice: 1.10 ,
      totalVolume: 90 ,
      tokenNumber: 2700,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342709/RVLTD_qjodok.avif",
      category:"meta",
    },
    {
      title: "Cool Cats",
      floorPrice: 0.89 ,
      totalVolume: 55 ,
      tokenNumber: 2200,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342708/Pepexel_d3pg0l.avif",
      category:"meta",
    },
    {
      title: "Pudgy Penguins",
      floorPrice: 3.40,
      totalVolume: 43 ,
      tokenNumber: 4500,
      image: "https://res.cloudinary.com/dd4xvwf8d/image/upload/v1738342708/ORL_oceans_rrajjl.avif",
      category:"meta",
    },
    ];